### ISSUE TITLE
Ubuntu ARPG install script.

### ISSUE THREAD

**Issue by Algomorph** [arpg/Documentation#1]
Hi,
I've written a [bash install script](https://github.com/Algomorph/UbuntuARPGinstall) for many packages (miniglog Sophus CVars Pangolin SceneGraph calibu Node HAL vicalib Kangaroo D-MoCap) and their dependencies, intended for use on Ubuntu.

It could be useful to mention it in the installation notes here.

**Comment by gsibley** [comment]
Hi,

This is great.  One thing you might be interested in: ARPG is using brew on
OSX now, and we had hoped to use linuxbrew to automate installation across
all flavors of linux (blue sky hope).

Installation is now as easy as:

brew tap arpg/coredev
brew install vicalib --HEAD

which will scoop up every dependency and build them, too.  NB linuxbrew
isn't as nice as it is on OSX, and may never be.  We're open to other
options -- rosdep maybe?

On Fri, May 1, 2015 at 8:54 AM, Gregory Kramida notifications@github.com
wrote:

> Hi,
> I've written an bash install script
> https://github.com/Algomorph/UbuntuARPGinstall for many packages
> (miniglog Sophus CVars Pangolin SceneGraph calibu Node HAL vicalib Kangaroo
> D-MoCap) and their dependencies, intended for use on Ubuntu.
> 
> It could be useful to mention it in the installation notes here.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/arpg/Documentation/issues/1.

## 

Gabe Sibley, PhD

Assistant Professor
Department of Computer Science

## University of Colorado, Boulder

**Comment by Algomorph** [comment]
The ideal solution for debian(-based) would be, off course, to integrate CPACK debian building taking dependencies into account, set up a ppa, and set up automatic deb package updates. I haven't dealt with this before.

P.S. I haven't tried this script in awhile, so I don't know if it will work at this point. It's pulling the latest trunk versions of everything, so it may be outdated. If anyone needs it and finds bugs, please report the issue in https://github.com/Algomorph/UbuntuARPGinstall.

**Comment by gsibley** [comment]
Good plan.  We are looking at getting CVars into debian testing proper.  If
you wanted to tackle Sophus with CPACK that would be fantastic.

On Mon, Nov 16, 2015 at 6:58 AM, Gregory Kramida notifications@github.com
wrote:

> The ideal solution for debian(-based) would be, off course, to integrate
> CPACK debian building taking dependencies into account, set up a ppa, and
> set up automatic deb package updates. I haven't dealt with this before.
> 
> P.S. I haven't tried this script in awhile, so I don't know if it will
> work at this point. It's pulling the latest trunk versions of everything,
> so it may be outdated. If anyone needs it and finds bugs, please report the
> issue in https://github.com/Algomorph/reco.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arpg/Documentation/issues/1#issuecomment-157059178.

## 

Gabe Sibley, PhD

Assistant Professor
Department of Computer Science

## University of Colorado, Boulder
